### ISSUE TITLE
In JratyServiceProvider.php line 32:

### ISSUE THREAD

**Issue by amirgee007** [escapeboy/jraty#3]
In JratyServiceProvider.php line 32:

  Call to undefined method Illuminate\Foundation\Application::share()

using that package and got that error

**Comment by escapeboy** [comment]
What version of Laravel are you using? There is no 5+ support currently. I should make a new version soon, but honestly didn't think someone still use it.

**Comment by amirgee007** [comment]
"laravel/framework": "5.4.*",

https://codecanyon.net/item/my-manga-reader-cms/12487949

trying to use this cms just got when i run composer update

**Comment by escapeboy** [comment]
Unfortunately even if I update the package for Laravel 5.4 it will be complete different and can't know if it will work with this cms. Maybe you should talk with them how they fixed it on their demo page.

But you can try this to fix it (at least this point). Try replacing register() method with this (in JratyServiceProvider.php):
```
$this->app->singleton('Jraty', function () {
      return new Jraty();
});
```
---
Another way is to include this file: https://github.com/escapeboy/jraty/blob/master/src/Escapeboy/Jraty/Jraty.php
Somewhere in your app/ folder. For example app/Services. It should be autoloaded (if not try composer dump-auto).
Then remove/comment line in composer.json and update without it.

**Comment by amirgee007** [comment]
thank you , working now...
